### PR TITLE
fix header sub menu try2

### PR DESCRIPTION
**Pull request by sigmaSd**

### CODE REVIEW

**Comment by sigmaSd** [comment]
I'm not 100% confident  that nothing broke

**Comment by sigmaSd** [comment]
Seems to work in my simple testing

**Comment by sigmaSd** [comment]
Superseeds https://github.com/denoland/dotland/pull/2584

**Comment by sigmaSd** [comment]
Fix https://github.com/denoland/dotland/issues/2586

**Review by crowlKats — APPROVED** [review]
LGTM, thanks

**Pull request merged**
