### PR TITLE
Fix the minus icon not appearing when expanding the expandable sections of the header

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Review by crowlKats — CHANGES_REQUESTED** [review]
This breaks hover on desktop.

**Comment by roj1512** [comment]
What hover do you mean?

**Comment by roj1512** [comment]
@crowlKats What about this?

**Comment by crowlKats** [comment]
You should be able to get this work by just moving the input to be the first item in the div and changing the children selectors; no need to add a new div.

**Comment by roj1512** [comment]
I tried that but I cannot select the nth-child(2) with twind, can I?

**Comment by crowlKats** [comment]
you could select the `even` child

**Review by crowlKats — APPROVED** [review]

**Pull request merged**
