### PR TITLE
remove symbol search

### LINKED ISSUE #2327: Symbol search results should prioritise default modules
Currently searching for `assert` returns quite a few clearly "internal" modules of a repo:

Third_Party_Modules___Deno

If a module has a default module, we should either not publish the symbols of the other modules inside that module _or_ ensure they are a much lower priority after other modules indexes.

In the above example, we would want to see `std` and `conditional_type_checks` before the other modules.

### LINKED ISSUE #2362: "serve" as default search term skews results
We are currently defaulting to "serve" as a search result, meaning it gets a lot of hits, skewing the results.  We need to figure a better way to manage this.

### LINKED ISSUE #2516: Global search shouldn't be global when in a module
If you are in std or a third party module and you open the search, you would more likely expect:

- it to default to symbol search
- default to only searching within the current module

The first one should be straight forward.  The second one should be possible, though might need some re-work of things.

cc/ @surma

### PR DESCRIPTION
**Pull request by crowlKats**
Towards #2634

Closes #2327
Closes #2362
Closes #2516

### CODE REVIEW

**Review by ry — APPROVED** [review]
LGTM - I'm interested to hear how much people complain

**Comment by sigmaSd** [comment]
This was very useful, why was it removed ?

**Comment by KnorpelSenf** [comment]
> I'm interested to hear how much people complain

I'd also like to complain, so now there are 2 people who found this useful :D

**Comment by sigmaSd** [comment]
I feel like people didn't know that this even exists, since it was not that much advertised and was not up for long. The problem now is even std symbols are not searchable anymore

**Pull request merged**
