### PR TITLE
feat: add pagination to search modal

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Comment by lucacasonato** [comment]
The page number is not reset when switching between tabs.

**Comment by crowlKats** [comment]
@lucacasonato fixed

**Comment by ry** [comment]
Screen Shot 2022-07-27 at 1 41 35 PM
pagination starts at -1

**Comment by crowlKats** [comment]
@ry apologies, should be fixed now

**Review by ry — APPROVED** [review]
LGTM

**Pull request merged**
