### PR TITLE
Remove cookie banner

### PR DESCRIPTION
**Pull request by piscisaureus**
We don't actually use any cookies, except to track whether the user has
dismissed the cookie banner.

Additionally, there is no legal requirement to ask for consent (GDPR) or
provide an opt-out (CCPA) to use this type of cookie.

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
We used to have cloudflare analytics on the page, which is what the banner was for.

**Comment by lucacasonato** [comment]
I think that was it at least

**Comment by piscisaureus** [comment]
> We used to have cloudflare analytics on the page, which is what the banner was for.

Hardly "functional cookies", but let's say bygones be bygones :)

**Comment by lucacasonato** [comment]
Actually no, was because _cfuid: https://github.com/denoland/dotland/issues/1429. That has since been removed tough

**Pull request merged**
