### PR TITLE
feat: add module landing page

### PR DESCRIPTION
**Pull request by crowlKats**
- [x] display current version
- [x] mobile view
- [ ] properly handle relative references in readmes
- [ ] import block

### CODE REVIEW

**Comment by kitsonk** [comment]
The display of the config is the same, irrespective of it being a `deno.json` or `deno.jsonc`.  Here is oak which has a `deno.jsonc`:

oak_v11_0_0___Deno

Either we should ensure it reflects the file, or we should change it do, `Contains Deno configuration` or something like that.

**Comment by lucacasonato** [comment]
Why is having a Deno config a good metric? I don't want packages to add a Deno config file just because it looks good on the /x landing page.

**Review by kitsonk — APPROVED** [review]
LGTM - good enough to land IMO once CI passes.  A few niggles but we can iterate on it.

**Comment by crowlKats** [comment]
> Why is having a Deno config a good metric? I don't want packages to add a Deno config file just because it looks good on the /x landing page.

@lucacasonato i wouldnt consider it a "good metric", its just an attribute

**Pull request merged**
