### PR TITLE
refactor: use algolia for module listing

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Comment by crowlKats** [comment]
The one thing missing is how to get total number of modules

**Comment by ry** [comment]
Why does it have 

import { start } from "[https://deno.land/x/fresh@1.0.0/server.ts](https://deno.land/x/fresh@1.0.0/server.ts?code)";

**Comment by crowlKats** [comment]
@ry what do you mean?

**Comment by ry** [comment]
Screen Shot 2022-08-04 at 5 26 26 PM

**Comment by crowlKats** [comment]
ah, that is completely unrelated to this PR, however it has been fixed earlier and is on main already

**Comment by ry** [comment]
can you merge with main?

**Comment by kitsonk** [comment]
@crowlKats I added `popularity_tag` as a "display facet" to the algolia search, which means I believe it should be returned on the results now, with the same values of `top_1_percent`, `top_5_percent`, `top_10_precent`, or `undefined` that we use elsewhere.

**Comment by kitsonk** [comment]
This is blocked on that we didn't have a filter to only include 3rd party modules in the list.  That is in a re-structured search index, but we need to integrate that back into this PR.

**Review by kitsonk — APPROVED** [review]
LGTM... awesome, this makes a huge difference.

**Pull request merged**
