### PR TITLE
fix: dont send click event to toggle for desktop header

### LINKED ISSUE #2591: Goofy header behavior
If you click on a section on the header, it will keep that section open even if the user's mouse leaves the hover area. This results in some goofy looking behavior in specific circumstances.

Reproc steps:
1. Click "Modules" text
2. Hover over "Docs"

Fix:
- Either remove on-click behavior or disable on-hover behavior after the user has clicked on another nav element

Screenshot 2022-11-15 at 2 43 59 PM

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #2591

### CODE REVIEW

**Comment by WittySmirk** [comment]
### This change breaks mobile because you can no longer open the menus:
no_mobile

**Comment by crowlKats** [comment]
@WittySmirk no it doesnt. this is only changed for the large breakpoint.

**Comment by WittySmirk** [comment]
@crowlKats yeah mb I messed up the diff and had the pointer-events-none out of the lg scope.

**Review by kt3k — APPROVED** [review]
LGTM

Also confirmed that this fixes the issue with desktop width, and keeps toggle behavior on mobile width.

**Pull request merged**
