### PR TITLE
fix: prevent twind preflight from overwriting img and video elements height attribute

### LINKED ISSUE #2279: Invalid image size rendering in README's
`deno.land/x` seems to overwrite height of images to `auto` which breaks images in README that specify `width` or `height` attributes.

On the top how it's supposed to look like (how github renders it) and on the bottom how it looks like.

image
image

### PR DESCRIPTION
**Pull request by Im-Beast**
Closes #2279

### CODE REVIEW

**Comment by crowlKats** [comment]
unsure if this really is the right approach; this should rather be fixed "properly"

**Comment by Im-Beast** [comment]
This is "proper" approach or at least I don't see other way around it.

Preflight applies `max-width: 100%` and `height: auto;` to `img,video` and if either height or width is present in CSS size attributes don't really work.

**Review by crowlKats — APPROVED** [review]
thanks

**Comment by crowlKats** [comment]
@Im-Beast could you rebase?

**Comment by Im-Beast** [comment]
Will do right now

**Comment by Im-Beast** [comment]
Done @crowlKats

**Pull request merged**
