### PR TITLE
Fix "Add module" Page UI

### LINKED ISSUE #2029: Paragraph spacing is very tight
There are three paragraphs here, but it's hard to tell:

image

Maybe we should increase the spacing?

https://deno.land/add_module

### PR DESCRIPTION
**Pull request by ije**
close #2029

### CODE REVIEW

**Comment by kt3k** [comment]
Spacing between sections looks better to me, but spacing between paragraphs still seems narrow to me. How about adding `mb-1` or `mb-2` for each paragraph (`<p>`)?

スクリーンショット 2022-03-02 15 52 42

(from https://dotland-fresh-q6et8wnspex0.deno.dev/add_module)

**Comment by kidonng** [comment]
The list below also seems to be a little dense (notice the overlapping code background):

image

**Comment by ije** [comment]
@kt3k @kidonng updated

**Review by kt3k — APPROVED** [review]
Looks much better now! LGTM

**Pull request merged**
