### PR TITLE
Revert "update fresh (#2207)"

### PR DESCRIPTION
**Pull request by crowlKats**
This reverts commit 69ff5b03f28c8eb29e40d649f5fe60f5e8fdf7de.

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
This also reverts the latest commit

**Comment by crowlKats** [comment]
@lucacasonato uhm, no?

**Review by lucacasonato — APPROVED** [review]
Sorry, the GH mobile app is thoroughly broken again. It showed me an incorrect diff again.

**Comment by lucacasonato** [comment]
Will fix this a different way

**Pull request closed without merging**
