### PR TITLE
Add showcase page

### PR DESCRIPTION
**Pull request by lambtron**
WIP. first rough pass at a /showcase page. very open to design and copy feedback!!

TODO:
- [ ] make responsive experience much better
- [ ] do we want to include logos?
- [ ] do we want to include on hover state?

### CODE REVIEW

**Review by ry — COMMENTED** [review]
where can i see a preview of this?

not found at https://dotland-bskgemnc1q50.deno.dev/showcase

maybe add links to the footer/header

**Comment by roj1512** [comment]
@ry https://dotland-fresh-tje3kypc0hf0.deno.dev/showcase

**Comment by crowlKats** [comment]
@ry whats the bug?

**Review by ry — APPROVED** [review]
LGTM

**Pull request merged**
