### PR TITLE
:sparkles: Explicitly require process

### PR DESCRIPTION
**Pull request by UltiRequiem**

### CODE REVIEW

**Comment by crowlKats** [comment]
whats the reasoning for this?

**Comment by UltiRequiem** [comment]
> whats the reasoning for this?

https://nodejs.org/api/process.html#process

> While it is available as a global, it is recommended to explicitly access it via require or import.

Sorry, forgot to put in the description.

**Comment by kt3k** [comment]
Node.js seems to have started recommending non-global `process` and `Buffer` since v16.x https://github.com/nodejs/node/pull/39043

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
