### PR TITLE
feat: TopBar component

### PR DESCRIPTION
**Pull request by bartlomieju**
Screenshot 2022-06-24 at 17 37 00

Screenshot 2022-06-24 at 17 39 05

### CODE REVIEW

**Comment by lucacasonato** [comment]
dotland-8xdpk984d48g deno dev_std@0 144 0

Broken on mobile

**Comment by bartlomieju** [comment]
@lucacasonato I'm aware, should have put WIP label, I just scratched the surface on this one.

**Comment by crowlKats** [comment]
there are now 2 weird bugs: if the tag in the version selector is present, for some reason the mobile toggle for the header shows up. second is the sizing of the deno logo in the header is different now for some reason, even though the header hasnt been touched

**Comment by crowlKats** [comment]
Current missing features from this design:

- how long ago a version came out
- dependency info

**Review by ry — APPROVED** [review]
LGTM

**Pull request merged**
