### PR TITLE
russian translate of deno docs

### PR DESCRIPTION
**Pull request by tvortsa**
propose my russian translation of deno docs

### CODE REVIEW

**Comment by kt3k** [comment]
Now translated website looks good to me https://deno-ru.vercel.app/ . Thank you for your effort!

Please send another PR, which only adds the item in translations.json (I've seen #1924 and #1925, but these have syntax errors in json and failed to deployed to vercel)

**Comment by tvortsa** [comment]
i was done all for now

пн, 1 нояб. 2021 г. в 10:39, Yoshiya Hinosawa ***@***.***>:

**Comment by kt3k** [comment]
@tvortsa 
We can't merge this PR because this changes our main site into russian..
Please create another branch which only includes the change in `translations.json` and send a PR with that branch.

**Comment by kt3k** [comment]
Ah, I've seen #1930 . Let's merge that one.

**Pull request closed without merging**
