### PR TITLE
fix: fix LP title width and add more padding for larger screens on all pages

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Comment by kt3k** [comment]
Looks fine to me, but what was the main motivation for this change?

**Comment by crowlKats** [comment]
I have been told that things overall are a bit too wide on larger screens, and needs adjustment

**Review by kt3k — APPROVED** [review]
Ok. Makes sense.

LGTM

**Comment by lucsoft** [comment]
> Looks fine to me, but what was the main motivation for this change?

This is a fix for #2604. This PR closes this issue.

**Pull request merged**
