### PR TITLE
Polish logo

### PR DESCRIPTION
**Pull request by LitoMore**
Related to https://github.com/denoland/dotland/pull/1836

Hi team. I did some polishing work for our logo.

### Enhancement

|Before|After|
|:-:|:-:|
|||
|image||

- ~~Made white parts transparent~~
- Converted strokes with borders to outlines
- Resolved all masks to paths
- Icon compressed with SVGO

### Discarded changes

<details>
<summary>Click to expand</summary>
<h4>Why `transparent`?</h4>

We can fit more situations (good for different foregrounds / backgrounds, and dark modes):

|Before|After|
|:-:|:-:|
|image|image|

If you still want those white colors that will be fine. It's very easy to switch colors now. (The old one cannot use transparent.)
</details>

### CODE REVIEW

**Comment by LitoMore** [comment]
One interesting thing:

image

Its "little mouth" is caused by the border. I cannot fix this because it comes from the original design. Changing the center border to the outside border will make our Deno a litter fatter. It is up to the designer to determine the "weight" of our Deno.

image image

**Comment by lucacasonato** [comment]
Hey @LitoMore. Thanks for the PR. The white in the rain drops is intentional. The logo does not look correct on dark themes otherwise (as the rain drops will be gray). The correct stylization is that the rain drops are always white.

**Comment by LitoMore** [comment]
OK. Let me change it to white.

**Review by ry — APPROVED** [review]
Thanks!

**Pull request merged**
