### PR TITLE
Revert "fix: manual overflow"

### LINKED ISSUE #2320: UI: cannot easily create links to parts of manual
There should be a UI element to make it easy to navigate to anchor links in the manual.  I thought there used to be, but now I have to inspect the page and figure out what the header ID is to generate the anchor.

### PR DESCRIPTION
**Pull request by crowlKats**
Reverts denoland/dotland#2310
Fixes #2320

### CODE REVIEW

**Comment by kitsonk** [comment]
So does it unfix something else?

**Comment by kidonng** [comment]
It unfixes https://github.com/denoland/dotland/pull/2304#issuecomment-1195477952

There is an alternative fix to that issue in https://github.com/denoland/dotland/pull/2307

**Comment by crowlKats** [comment]
Yea, i will then merge @kidonng 's PR after this lands, its good enough for now

**Comment by crowlKats** [comment]
@kidonng it always has looked like that on the manual

**Comment by kidonng** [comment]
> @kidonng it always has looked like that on the manual

I don't know, it's just a minor issue and I mentioned it in case in may you want to adjust it.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
