### PR TITLE
feat(module): sticky sidebar

### PR DESCRIPTION
**Pull request by sno2**
Not sure why there are formatting differences as I'm using `deno fmt` 🤷‍♂️

### CODE REVIEW

**Comment by sno2** [comment]
one sec it changed the order of the thing on the top on mobile - didn't realize that

**Comment by sno2** [comment]
Alright, should be ready for review now.

**Comment by sno2** [comment]
Hello @crowlKats , can you please review this if you have any time?

**Comment by crowlKats** [comment]
ugh, the reformatting makes it quite annoying

**Review by crowlKats — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
