### PR TITLE
fix: Links to source are broken

### LINKED ISSUE #2548: Links to source are broken
Reproduction steps:

- Goto https://deno.land/std@0.160.0?doc
- Click the goto source link
- The link will be `https://deno.land/std@0.160.0?doc?source` instead of `https://deno.land/std@0.160.0?source` and take you to the wrong page.

### PR DESCRIPTION
**Pull request by onishi-kohei**
fix #2548

### CODE REVIEW

**Comment by crowlKats** [comment]
this should rather clone the URL, delete the doc search param and add the source search param instead

**Comment by onishi-kohei** [comment]
@crowlKats 
Do you mean to replace "?doc" in url.href with "?source"?

**Comment by crowlKats** [comment]
yes, but using `url.searchParams`

**Comment by crowlKats** [comment]
Thanks for the PR. We don't use this repository anymore, as the website went closed-source, however I have backported your PR in said repository.

**Pull request closed without merging**
