### PR TITLE
chore: update fresh

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM, nice work!

**Comment by kt3k** [comment]
BTW what is `status/:id` page for? (I first realized it exists)

**Comment by crowlKats** [comment]
@kt3k I believe its for viewing the status of a release of a /x/ module. I think you can get the status url from a delivery of the github webhook. but yea i didnt know about it either until i had to refactor it when doing the fresh rework. doubt anyone really knows about it...

**Comment by kt3k** [comment]
@crowlKats Thanks. Right, it was included in webhook payload response.

スクリーンショット 2022-05-04 15 17 55

https://deno.land/status/627219dde71df9d9d790481b

Looks like we need to keep it

**Pull request merged**
