### PR TITLE
fix(search): handle ctrl+k and / shortcuts

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
Please add a check to ensure that the user does not have an `input` field focused at the time of entering the `/`, because otherwise we will open the search while they are typing in some other field.

**Comment by crowlKats** [comment]
@lucacasonato done

**Comment by lucacasonato** [comment]
doesn't work after you select then unselect an input field

**Comment by crowlKats** [comment]
it does for me..

**Review by lucacasonato — APPROVED** [review]
mh, now it's working for me too

**Pull request merged**
